### ISSUE TITLE
Record as a term

### ISSUE THREAD

**Issue by adoyle** [geojson/geojson-text-sequences#15]
I'm noting, not raising a stop-the-presses issue.

The term 'record' may be less familiar to people who have recently become involved in information processing than it is to those of us who have been there for a long time. In section 1 of the draft, the term is used 4 times. All but once, it's used as a noun, but the third use ('record GeoJSON') uses it as an adjective, or perhaps a compound noun. In this RFC it's pretty much synonymous with 'GeoJSON text'

Interestingly, neither RFC 7464, nor RFC 20 define the term. RFC 20 does indicate 'RS' is one of three 'information separators' with no clearly defined semantics other than they are optional, and are to be used in a hierarchy.

We can't presume to define what is meant by the term record in the other RFCs, but we can define what the term means in this one. 

Section 2, paragraph 1, essentially is the definition of what is meant by 'record' in the context of this document. The question in my mind is how to best make that clear since use of 'record' precedes that paragraph.

**Comment by sgillies** [comment]
I've been using "record" to mean the text between record separators, but I think "text" would be more precise except in the first instance, where we can say "value" as in RFC 7464.
