### ISSUE TITLE
+json-seq should be a proper structured syntax suffix

### ISSUE THREAD

**Issue by dret** [geojson/geojson-text-sequences#19]
the current draft assumes that +json-seq can be used in a media type name. right now that;'s not the case. https://tools.ietf.org/html/draft-json-seq-suffix should change this, but this will block our draft. let's hope we can get the suffix approved quickly, and then move forward with the text sequences draft. i'll update this issue for any new from the suffix registration.
in case you're interested in the draft's sources, they live here: https://github.com/dret/I-D/tree/master/json-seq-suffix

**Comment by dret** [comment]
https://tools.ietf.org/html/draft-wilde-json-seq-suffix is the updated draft (i got the name wrong the first time around).

**Comment by dret** [comment]
things are moving, slowly but hopefully surely...

**Comment by sgillies** [comment]
Done.
