### ISSUE TITLE
Copy over mardown/pandoc/xml2rfc framework from draft-geojson

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-text-sequences#2]
@dret what do you think about reusing the framework @sdrees set up for draft-geojson? The use of markdown is a great fit for GitHub, which renders the body nicely.

**Comment by dret** [comment]
i haven't used that one so far, but even an old dog should be able to learn new tricks, right? being an XML dinosaur, all of https://github.com/dret/I-D so far uses the good old "write xml2rfc XML by hand" workflow. so let's do what the cool kids do this time!

**Comment by sgillies** [comment]
Done! Note that the content is still that of the other repo.

**Comment by dret** [comment]
thanks! let's see how the core I-D progresses. one way or the other, once the sequences are RFC-blessed, we should start thinking about how to use them.
