### ISSUE TITLE
Start a Python reference implementation project

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-text-sequences#3]
Hey @geojson/owners @geojson/contributors @geowurster any objections to me adding a new repo in the geojson org for a Python implementation of feature sequences?

**Comment by adoyle** [comment]
Good idea.

##

**Comment by geowurster** [comment]
:+1:

**Comment by mpdaly** [comment]
:+1:

**Comment by sgillies** [comment]
https://github.com/geojson/py-feature-sequences
