### ISSUE TITLE
No header record

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-text-sequences#6]
In the past, I've been interested in the possibility of a "header record" for GeoJSON text sequences, but now I think this is not worth specifying.

Say you want to turn a directory full of spatial data files into a stream of GeoJSON features using a program like [fio-cat](https://github.com/Toblerity/Fiona/blob/master/docs/cli.rst#cat). You couldn't know the total number of features or bounding box of all features without reading every file first. And if you were continually adding files to the input of the program, you could _never_ know the number of features or their bounding box.

Stream writers that _do_ have this kind of information can communicate it to stream readers out of band.

**Comment by dret** [comment]
On 2016-03-14 19:44, Sean Gillies wrote:

> In the past, I've been interested in the possibility of a "header
> record" for GeoJSON text sequences, but now I think this is not worth
> specifying.
> Stream writers that /do/ have this kind of information can communicate
> it to stream readers out of band.

i think that's a good way to handle this. header records would come with 
a lot of questions about the model for that record, so they would turn 
into a modeling exercise of their own, without even knowing what kind of 
information applications might find useful.

somebody could invent this by using geojson's extensibility and putting 
that header info in the first geojson object, for example. that might be 
kind of a hack, but as long as the overall sequence still would be a 
proper geojson text sequence, it would solve this problem and maybe at 
some point could be turned into a recommendation of its own.
